"""create role tables and seed role names

Revision ID: 2f14b2c6ae9a
Revises: aac3c2aa1cea
Create Date: 2023-11-13 23:52:37.825004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f14b2c6ae9a'
down_revision = 'aac3c2aa1cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    role_names = ['admin', 'basic', 'advanced']  # Add your role names here
    connection = op.get_bind()

    role_table = sa.Table('role', sa.MetaData(), autoload_with=connection)

    for name in role_names:
        connection.execute(role_table.insert().values(name=name))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_table('user_role')
    # ### end Alembic commands ###
