"""create setting table

Revision ID: c4b5a3bb3c80
Revises: 2f14b2c6ae9a
Create Date: 2023-11-14 02:57:25.928291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b5a3bb3c80'
down_revision = '2f14b2c6ae9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    # ### end Alembic commands ###
